<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7256d33762ee46c756ae2eb6d9c3a1ea
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7256d33762ee46c756ae2eb6d9c3a1ea::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7256d33762ee46c756ae2eb6d9c3a1ea::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7256d33762ee46c756ae2eb6d9c3a1ea::$classMap;

        }, null, ClassLoader::class);
    }
}
